apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  tracing:
    samplingRate: '1'
    otel:
      endpointAddress: 'http://localhost:4318'
      isSecure: false
      protocol: 'http'
  features:
    - name: SchedulerReminders
      enabled: false
